name: Issue
description: Ask a question or report a problem with BHDS or the documentation
labels: ['Bug', 'untriaged']
body:
  - type: markdown
    attributes:
      value: |
        Please use our Feature Request template for feature requests.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a short description of the problem.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen?
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead of the expected behavior?
      value: |
        Wrap animated gifs/videos in a details tag:
        <details>
          <summary>Summary of your gif(s)</summary>
          <img src="..." alt="Description of what the gif shows">
        </details>
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a reduced test case with a code sandbox.
      value: |
        [Link to sandbox]()
        1. 
        2.
        3.
  - type: dropdown
    id: bhds-components
    attributes:
      label: Are you using BHDS components?
      options:
        - 'Yes'
        - 'No'
  - type: input
    id: bhds-version-number
    attributes:
      label: BHDS version number
  - type: input
    id: browser
    attributes:
      label: Browser
  - type: input
    id: device
    attributes:
      label: Device
